//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1emlakPortali.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evler()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public string evId { get; set; }
        public int evKat { get; set; }
        public int evFiyat { get; set; }
        public string evAdres { get; set; }
        public string evSatilik { get; set; }
        public string evKiralik { get; set; }
        public string evEsya { get; set; }
        public int evOdaSayisi { get; set; }
        public string evGorsel { get; set; }
        public string evKatId { get; set; }
        public int evKodu { get; set; }
        public string evSatilikKiralik { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
